define({
  "START_SCREEN": 0,
  "GAME_OVER": 1,
  "WHITE_START_PLACE": 2,
  "BLACK_START_PLACE": 3,
  "WHITE_PLACING": 4,
  "BLACK_PLACING": 5,
  "WHITE_START_SHOOT": 6,
  "BLACK_START_SHOOT": 7,
  "WHITE_SHOOTING": 8,
  "BLACK_SHOOTING": 9,
  "WHITE_SHOT": 10,
  "BLACK_SHOT": 11
});